name: Deploy to EC2

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Pull latest code and restart application
        run: |
          # Navigate to the application directory
          cd /home/ubuntu/timepulse_deploy/TimePulse

          # Reset to remote state (discard local changes)
          git fetch origin deploy
          git reset --hard origin/deploy

          export PATH=$PATH:/usr/local/bin
          pm2 reload timepulse-frontend
          pm2 reload timepulse-server
          pm2 reload timepulse-engine
          pm2 save
          
      - name: Check PM2 status
        run: |
          export PATH=$PATH:/usr/local/bin
          pm2 status